language: java
script:
- mvn clean install
- cd com.wireframesketcher.model.repository.remote
- mvn install
env:
  global:
  - secure: J1H9arE3g6qs7QZHKUJmdCucD6DvyVDu723ET+6YjrnAf9EloUmdI/BrdqT5Mm86CKLR1y1v8CoZd0N8qdOODs2vWjmzBvSJYxdeeOs0f6RYRmYp6yyfZfyExbRKFbzSznEzYox4tK7oUpJdRE6dd2hQ1Pp3I/DJSEcu9whCnVBiMYl2rob87zCuzwe73fab78t2fY6CyNxAN7cp9MHEuAQIzM5HdNcD6FFVc/cv3J7WaQneBvBvjRS0uBBxu1Fd9aTVJ2ypgo7IO2qr/Jcw6c/kmWB6NSkQHhIBrTdgA9uhwdCr4JShoC4V3TZlxlDRHkCB16puUEjqKcf2Pg9lGB44X7cmgPkRcifWwanUc3JWPr4DNGsX4oZrVSfMZcTCdEmU48Z/23dC3tDNSUicFX/6NQJguEvweJKH13JbEj6x5I/dH9bCU3dcUJqM1wVJ8yKsP99+wWPsGGg4WTnwhFsz8cHQ1dmMPHUHQA8AgXl/VgQfMr4WO833kuMJzivsaCxZ5mKRYvabwboY96XPxQYsnEv2ER/PXHwTIl1H9klHfvF7L2ejrTGsZuzfAAvjk0i+BzcZZgl8N1zYic1o1c1DZNNLDJv88u/F3IsGGljK3U7l+hSdZ0owLuiftPwShNNHgJ9tNKqdgiBgm5xLYliL+tR6cbyHsFodmmJ/J2c=
  - secure: bbS1pYh9MGC+44sMU3qeqIrr09fGToIyOuY97zviqaXuyRuqoINFOizP5BX/HFtm683Jx2yR212bJFCimayaVT1DPG1CcMv2eKSxRbtTfnv9ddmsTnKWEI7GwwcAPsi1mXOgg9UnXkd6jAt3ZN2sNjAwTs9mDZ/fNpW9fiorP91glzBRTGXrvI3KkKa6rq+GyxYrhqJzMsknxZ+q8ydApiDt2VhiQ05iHfmuE+EtQwLow4UXYzppMqoN5Urn9uxuQw0YK8BJGaUWCWmF5+6E72widWmSixwXyR488O4ei7Js4quICs5GRIohwTfrlOyjyL4N6ay543KhW2ltRJAj+8dfvvVnSZOy43PbduDr4QaYErF1MdcVxBXRpB4WduFMlG6lCZ81SmdJQfN26bTghAkQvqjl+osOuuOQsW9O4jq/x672EaQzgTO4TUbJAjEeNX5Q0nJMH8z4Bh5tUhdAyZ85saq3KWVucW/qKYHiYxwv1yZGzPNhOISoMG2f4ak93peTPLIendEoQRKJLeeufScbQm/Xh+uj+6t1ML6Z8fb5tF6Hu5pyjYu2oyUCLCoH0O/UEOH9/as3DIU8iPlrfs+0fPFmmzbSt5fY03ggQf6b8u/xoszL0E8+izHrmSP4LyFH7kjrB1L5fg7P3FjceBgQlxTV0aBJvHASpP/JIf4=
after_success: find ./target/repository/ -type f -exec curl --ftp-create-dirs -T {}
  -u $FTP_USER:$FTP_PASSWORD ftp://boomslang.org/updates/boomslang-wfs/repository/{}
  \;
deploy:
  provider: releases
  api_key:
    secure: DSfTA5mu69GdWOA8Bhsltq8eDzGGAaaIWK0w1fJWjgehD2N4hyaZSZ/NBNwTDQw85WPHVsYOrsygfMghovuDe0z0EY4VuDV6HsOqz/MJEPIr8xPX30Kw7Ml9i1HV+U7BFCWoipfzzV2K19na9t3O8UEU7qp007I6ED6TXiHCCW6VocD337PVM/uhAvW0hGNpxqq81yomHNBXgbKkIjZIPujOs6W93wn6+XYthBHQVYx9R74ihTtFrxXf6e3Uyj0XBJnpMn6EK6LKkng4Di8qi5TLsi3eW40zI69YYZe4zYsoBrsZ/mq76QJHJ2q2luw48M/viwbnpxEO0cwF9dcMnN1/DkH4GqcgOmY7+khZmzzk4C7/yURIalS43l2DzFOwg6SVh9IM0wjHqntQyCBe4/bDNSAjnQX/a/b+eBRsBkg/9ZTxu1jmXAlPYWZ4sLgy35d409UCSs/S1GW9hULAWhJZZRrimsQrlhPrehXyisKQ4xxaN418uOyn4sb2g2gLXho7ehzGsOdxD7ZUfq8CnwkkYKk9bP9KlOLWLNU3pbWftkQparOmhh2jHxELyRNUUjwjw8iM+wNnBMapAIGn1DTk2tGDGYfBg3xh63ZMT/PHyRAVUpjw7Oz5q6G+dxgqUURwbNU3+eh6PAPEQ/5fkI29lso27tLKC8KaqDHjIiM=
  file: com.wireframesketcher.model.repository.remote/target/repository/*
  skip_cleanup: true
  on:
     repo: Jose-Badeau/boomslang-wireframesketcher

