language: java
script:
- mvn clean install
- cd com.wireframesketcher.model.repository.remote
- mvn install

after_success: curl -T ./target/repository/artifacts.jar -uhbuender:dcf3076d7096ed50497ad4dae2ebe22f72d79a3b https://api.bintray.com/content/jose-badeau/boomslang-wireframesketcher/boomslang-package/010/repository